# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yonet\Desktop\designerUI\resimcontrol.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import Screens.resources_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_resiminput(object):
    def setupUi(self, ImageWindow):
        ImageWindow.setObjectName("ImageWindow")
        ImageWindow.resize(550, 394)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/hackers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImageWindow.setWindowIcon(icon)
        ImageWindow.setStyleSheet("background-image: url(:/images/background.jpg);")
        self.centralwidget = QtWidgets.QWidget(ImageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 611, 411))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit1.setGeometry(QtCore.QRect(60, 250, 421, 31))
        self.lineEdit1.setText("")
        self.lineEdit1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit1.setObjectName("lineEdit1")
        self.labelText = QtWidgets.QLabel(self.groupBox)
        self.labelText.setGeometry(QtCore.QRect(90, 30, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelText.setFont(font)
        self.labelText.setAlignment(QtCore.Qt.AlignCenter)
        self.labelText.setObjectName("labelText")
        self.gonderButton = QtWidgets.QPushButton(self.groupBox)
        self.gonderButton.setGeometry(QtCore.QRect(160, 310, 211, 28))
        self.gonderButton.setObjectName("gonderButton")
        self.imageLabel = QtWidgets.QLabel(self.groupBox)
        self.imageLabel.setGeometry(QtCore.QRect(90, 100, 351, 111))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        ImageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 26))
        self.menubar.setObjectName("menubar")
        ImageWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageWindow)
        self.statusbar.setObjectName("statusbar")
        ImageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ImageWindow)
        QtCore.QMetaObject.connectSlotsByName(ImageWindow)

    def retranslateUi(self, ImageWindow):
        _translate = QtCore.QCoreApplication.translate
        ImageWindow.setWindowTitle(_translate("ImageWindow", "Resim"))
        self.labelText.setText(_translate("ImageWindow", "Resimdeki Sayıyı Giriniz"))
        self.gonderButton.setText(_translate("ImageWindow", "Gönder"))




